name: Pre Commit Checks
on: [push]
jobs:
  format:
    name: 📑 Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v7

      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: 🪄 Formatting
        run: make cleanup install autoflake isort black CHECK=1

  type:
    name: 👨‍⚕️ Type Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v7

      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: ⌨️ Type checking
        run: make cleanup install mypy
